### ISSUE TITLE
Unable to find a specification for `ParseTwitterUtils`

### ISSUE THREAD

**Issue by bchapin** [ParsePlatform/ParseTwitterUtils-iOS#38]
Trying to add ParseTwitterUtils-iOS to my project. Pod reports it is unable to find a specification for ParseTwitterUtils.

**Comment by nlutsenko** [comment]
Not sure why this fails in your case, since we have `ParseTwitterUtils` as a CocoaPod and it's even visible on CocoaPods website - https://cocoapods.org/pods/ParseTwitterUtils

I would suggest running `pod repo update` as well as making sure you have the latest version of CocoaPods by running something like `sudo gem update cocoapods` (sudo is of course optional, and purely depends on your installation of rubygems).
